### ISSUE TITLE
AlreadyDisposedException is thrown when closing project

### ISSUE THREAD

**Issue by fan-tom** [fan-tom/intellij-codeowners#147]
```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.openapi.vcs.FileStatusManager because container is already disposed (container=Project(name=server2, containerState=DISPOSE_COMPLETED, componentStore=/Users/morph/dev/Projects/miro/server2) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:695)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:629)
	at com.intellij.openapi.vcs.FileStatusManager.getInstance(FileStatusManager.java:13)
	at com.github.fantom.codeowners.CodeownersManager$debouncedStatusesChanged$1.task(CodeownersManager.kt:98)
	at com.github.fantom.codeowners.util.Debounced.run$lambda$0(Debounced.kt:26)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by seregamorph** [comment]
Reproduced on IDEA CE 2023.1:
```
Worker exited due to exception

java.lang.AssertionError: Cannot create com.intellij.openapi.vcs.FileStatusManager because container is already disposed (container=Project(name=jOOQ, containerState=DISPOSE_COMPLETED, componentStore=/Users/morph/dev/Projects/3rdparty/jOOQ) (disposed))
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:54)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:240)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:288)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.openapi.vcs.FileStatusManager because container is already disposed (container=Project(name=jOOQ, containerState=DISPOSE_COMPLETED, componentStore=/Users/morph/dev/Projects/3rdparty/jOOQ) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:736)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at com.intellij.openapi.vcs.FileStatusManager.getInstance(FileStatusManager.java:22)
	at com.github.fantom.codeowners.CodeownersManager$debouncedStatusesChanged$1.task(CodeownersManager.kt:98)
	at com.github.fantom.codeowners.util.Debounced.run$lambda$0(Debounced.kt:26)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 8 more
```
