### ISSUE TITLE
com.intellij.diagnostic.PluginException: com.github.fantom.codeowners.reference.CodeownersGithubOwnerReference$MyFakePsiElement cannot be presented 

### ISSUE THREAD

**Issue by vasilep** [fan-tom/intellij-codeowners#165]
```
com.intellij.diagnostic.PluginException: com.github.fantom.codeowners.reference.CodeownersGithubOwnerReference$MyFakePsiElement cannot be presented [Plugin: fantom.codeowners]
  at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
  at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
  at com.intellij.codeInsight.navigation.UtilKt.presentationError(util.kt:110)
  at com.intellij.codeInsight.navigation.UtilKt.targetPresentation(util.kt:93)
  at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computePresentation(PsiElementDocumentationTarget.kt:67)
  at com.intellij.platform.backend.documentation.impl.ImplKt.documentationRequest(impl.kt:17)
  at com.intellij.lang.documentation.ide.impl.DocumentationTargetHoverInfoKt$calcTargetDocumentationInfo$1$request$1.invoke(DocumentationTargetHoverInfo.kt:41)
  at com.intellij.lang.documentation.ide.impl.DocumentationTargetHoverInfoKt$calcTargetDocumentationInfo$1$request$1.invoke(DocumentationTargetHoverInfo.kt:36)
  at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
  at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
  at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:92)
  at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$1.invoke(InternalReadAction.kt:91)
  at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
  at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
  at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
  at com.intellij.openapi.progress.CancellationKt.executeWithJobAndCompleteIt(cancellation.kt:126)
  at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$1$lambda$0(cancellableReadAction.kt:49)
  at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
  at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$1(cancellableReadAction.kt:47)
  at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
  at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
  at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:45)
  at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:91)
  at com.intellij.openapi.application.rw.InternalReadAction.access$tryReadCancellable(InternalReadAction.kt:15)
  at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:77)
  at com.intellij.openapi.application.rw.InternalReadAction$tryReadAction$2.invoke(InternalReadAction.kt:72)
  at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
  at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
  at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
  at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:193)
  at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:72)
  at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
  at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
  at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:43)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
----------------------------------------------------------------
This crashes frequently on my dev system running on CentOS 7: `CentOS Linux release 7.9.2009 (Core)`, with the v0.5.0 plugin installed inside **IntelliJ 2023.1.1** Community Edition:
```
IntelliJ IDEA 2023.1.1 (Community Edition)
Build #IC-231.8770.65, built on April 27, 2023
Runtime version: 17.0.7+7 amd64
VM: OpenJDK 64-Bit Server VM by Eclipse Adoptium
Linux 3.10.0-1160.90.1.el7.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 7
Non-Bundled Plugins:
    fantom.codeowners (0.5.0)
    idea.plugin.protoeditor (231.8109.91)
Kotlin: 231-1.8.21-IJ8770.65
Current Desktop: GNOME-Classic:GNOME
```

**Comment by vasilep** [comment]
@fan-tom, do you think this exception is due to some non-standard syntax in my `CODEOWNERS` file?

**Comment by joklek** [comment]
I can found a discussion about a similar issue on another plugin https://github.com/lppedd/idea-conventional-commit/issues/68. Haven't looked into how `CodeownersGithubOwnerReference` works exactly, but posting here just in case someone finds it useful

**Comment by fan-tom** [comment]
Duplicates #63
